version: 0.2
phases:
  pre_build:
    commands:
      - echo "This is going to be the pre build stage\n Its the npm version"
      - npm --version
  build:
    commands:
      - npm install package.json
      - npm audit fix --force
      - npm pm_start
  post_build:

    commands:
      - echo "this is the post build stage"
artifacts:
  files:
    - '**/*'