version: 0.2
phases:
  pre_build:
    on-failure: ABORT | CONTINUE
    commands:
      - echo "This is going to be the pre build stage\n Its the npm version"
      - npm --version
  build:
    on-failure: ABORT | CONTINUE
    commands:
      - npm install package.json
  post_build:
    on-failure: ABORT | CONTINUE
    commands:
      - echo "this is the post build stage"
artifiacts:
  files:
    - '**/*' 